version: 1
update_configs:
  - package_manager: "python"
    directory: "/requirements"
    update_schedule: "daily"
    default_labels:
      - "dependencies"
    allowed_updates:
      - match:
          dependency_name: "catalyst"

  - package_manager: "docker"
    directory: "/docker"
    update_schedule: "daily"
    default_labels:
      - "dependencies"
