shared:
  image_size: &image_size 224
  loss_key: &loss_key "embeddings_loss"

model_params:
  model: MultiHeadNet
  image_size: *image_size
  encoder_params:
    arch: resnet18
    pretrained: True
    frozen: True
    pooling: GlobalConcatPool2d
  embedding_net_params:
    hiddens: [256]
    layer_fn: {"module": "Linear", "bias": False}
    norm_fn: BatchNorm1d
    activation_fn: ReLU
    dropout_fn: Dropout
    residual: "soft"
  heads_params:
    logits: &num_classes 2

args:
  expdir: "src"
  logdir: &logdir "./logs/classification"

stages:

  state_params:
    main_metric: &reduce_metric accuracy01
    minimize_metric: False

  data_params:
    num_workers: 4
    batch_size: 64
    per_gpu_scaling: True
    one_hot_classes: *num_classes

  transform_params:
    _key_value: True

    train:
      transform: A.Compose
      transforms:
        - &pre_transforms
          transform: A.Compose
          transforms:
            - transform: A.LongestMaxSize
              max_size: *image_size
            - transform: A.PadIfNeeded
              min_height: *image_size
              min_width: *image_size
              border_mode: 0  # cv2.BORDER_CONSTANT
              value: 0
        - &hard_transforms
          transform: A.Compose
          transforms:
            - transform: A.Cutout
              num_holes: 4
              max_w_size: 56  # 224 // 4
              max_h_size: 56  # 224 // 4
              p: 0.5
            - transform: A.ShiftScaleRotate
              shift_limit: 0.1
              scale_limit: 0.1
              rotate_limit: 15
              border_mode: 2  # cv2.BORDER_REFLECT
              p: 0.5
            - transform: A.IAAPerspective
              scale: [0.02, 0.05]
              p: 0.5
            - transform: A.OneOf
              transforms:
                - transform: A.HueSaturationValue
                  p: 0.5
                - transform: A.ToGray
                  p: 0.5
                - transform: A.RGBShift
                  p: 0.5
                - transform: A.ChannelShuffle
                  p: 0.5
            - transform: A.RandomBrightnessContrast
              brightness_limit: 0.5
              contrast_limit: 0.5
              p: 0.5
            - transform: A.RandomGamma
              p: 0.5
            - transform: A.CLAHE
              p: 0.5
            - transform: A.JpegCompression
              quality_lower: 50
              p: 0.5
        - &post_transforms
          transform: A.Compose
          transforms:
            - transform: A.Normalize
            - transform: A.ToTensor
    valid:
      transform: A.Compose
      transforms:
        - *pre_transforms
        - *post_transforms
    infer:
      transform: A.Compose
      transforms:
        - *pre_transforms
        - *post_transforms

  criterion_params:
    criterion: CrossEntropyLoss

  # train head
  stage1:

    state_params:
      num_epochs: 20

    optimizer_params:
      optimizer: Adam
      lr: 0.001
      weight_decay: 0.0001

    scheduler_params:
      scheduler: MultiStepLR
      milestones: [10]
      gamma: 0.3

    callbacks_params: &callbacks
      loss:
        callback: EmbeddingsCriterionCallback
        emb_l2_reg: -1
        input_key: targets
        embeddings_key: embeddings
        output_key: logits
        prefix: *loss_key
      accuracy:
        callback: AccuracyCallback
        num_classes: *num_classes
      cm:
        callback: ConfusionMatrixCallback
        input_key: targets
        output_key: logits
        num_classes: *num_classes
      optimizer:
        callback: OptimizerCallback
        loss_key: *loss_key
      scheduler:
        callback: SchedulerCallback
        reduce_metric: *reduce_metric
      saver:
        callback: CheckpointCallback

  # tune whole network
  stage2:

    state_params:
      num_epochs: 10

    optimizer_params:
      optimizer: SGD
      lr: 0.0001

    scheduler_params:
      scheduler: MultiStepLR
      milestones: [10]
      gamma: 0.3

    callbacks_params: *callbacks

  infer:

    data_params:
      num_workers: 4
      batch_size: 64
      per_gpu_scaling: True
      in_csv: null
      in_csv_train: null
      in_csv_valid: "./data/dataset_valid.csv"
      in_csv_infer: "./data/dataset_train.csv"
      datapath: "./data/dataset"
      one_hot_classes: null

    callbacks_params:
      loader:
        callback: CheckpointCallback
      infer:
        callback: InferCallback
        out_dir: *logdir
        out_prefix: "/predictions/"
