shared:
  class_names: &class_names {{ class_names }}
  image_size: &image_size {{ max_image_size }}

model_params:
  image_size: *image_size
  heads_params:
    logits: &num_classes {{ num_classes }}

args:
  expdir: {{ expdir }}

stages:
  state_params:
    main_metric: &reduced_metric auc_class/_mean
    minimize_metric: False

  data_params:
    num_workers: {{ num_workers }}
    batch_size: {{ batch_size }}
    per_gpu_scaling: True
    one_hot_classes: *num_classes
    balance_strategy: {{ balance_strategy }}
    in_csv_train: {{ dataset_path }}/dataset_train.csv
    in_csv_valid: {{ dataset_path }}/dataset_valid.csv
    datapath: {{ dataset_path }}/images

  transform_params:
    transform: A.Compose
    transforms:
      - transform: A.Resize
        height: *image_size
        width: *image_size
      - transform: A.Normalize
      - transform: catalyst.ToTensor

  criterion_params:
    _key_value: True

    class:
      criterion: {{ criterion }}
    embeddings:
      criterion: EmbeddingsNormLoss

  callbacks_params: &callbacks
    loss_class:
      callback: CriterionCallback
      input_key: targets
      output_key: logits
      prefix: loss_class
      criterion_key: class
      multiplier: 1.0
    loss_embeddings:
      callback: CriterionCallback
      output_key: embeddings
      prefix: loss_embeddings
      criterion_key: embeddings
      multiplier: 0.0
    loss_aggregator:
      callback: MetricAggregationCallback
      prefix: &aggregated_loss loss
      metrics: [loss_class, loss_embeddings]
      mode: "sum"
      multiplier: 1.0

    accuracy_class:
      callback: AccuracyCallback
      input_key: targets
      output_key: logits
      prefix: accuracy_class
      num_classes: *num_classes
    auc_class:
      callback: AUCCallback
      input_key: targets_one_hot
      output_key: logits
      prefix: auc_class
      class_names: *class_names
      num_classes: *num_classes
    f1_class:
      callback: F1ScoreCallback
      input_key: targets_one_hot
      output_key: logits
      activation: Softmax
    cm_class:
      callback: ConfusionMatrixCallback
      input_key: targets
      output_key: logits
      prefix: cm_class
      class_names: *class_names
      num_classes: *num_classes

    optimizer:
      callback: OptimizerCallback
      loss_key: *aggregated_loss
    scheduler:
      callback: SchedulerCallback
      reduced_metric: *reduced_metric
    saver:
      callback: CheckpointCallback

  infer:
    state_params:
      num_epochs: 1

    data_params:
      in_csv: null
      in_csv_train: null
      in_csv_valid: null
      in_csv_infer: {{ dataset_path }}/dataset_infer.csv
      datapath: {{ dataset_path }}/images
      one_hot_classes: null
      balance_strategy: null

    callbacks_params:
      loader:
        callback: CheckpointCallback
        resume: checkpoints
      infer:
        callback: InferCallback
        out_prefix: {{ dataset_path }}/predictions/
